# Checks to make sure that the ofYaml/toYaml
# procs generated by deriveYaml are exposed publicly
#
import
  yanyl,
  test_utils/yaml_testing,
  unittest

var sample = """
s: hello other module
i: 78
"""

var o: MockObj = ofYamlStr(sample, MockObj)

check o.s == "hello other module"
check o.i == 78

checkRoundTrip o